variable "prod_region" {}
variable "prod_cidr_block" {}
variable "prod_sub_cidr_block" {}
variable "prod_ami_image" {}
variable "prod_instance_type" {}
variable "prod_bucket_name" {}
variable "prod_allocated_storage" {}
variable "prod_db_name" {}
variable "prod_engine" {}
variable "prod_engine_version" {}
variable "prod_instance_class" {}
variable "prod_username" {}
variable "prod_password" {}
variable "prod_parameter_group_name" {}
variable "prod_skip_final_snapshot" {}
variable "key_name" {}
variable "wordpress_prefix" {}
